### ISSUE TITLE
Peer dependency conflicts

### ISSUE THREAD

**Issue by ghost** [Postavshik/ngx-cypress-test#28]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request
* [ ] question about the decisions made in the repository

### Issue description

**Current behavior:**
When following the instructions of the udemy course, I ran into a peer dependency issue. These are the exact steps I followed:
1. Pulled the repository
2. executed npm install
3. executed npm start
4. executed npm install cypress --save-dev

After step 4, I got the error messages as in the attached err.txt (peer dependency conflicts)
Was able to resolve that by using a --legacy-peer-deps and cypress@10.0

**Expected behavior:**
Should install and use cypress just like the course instructions say

**Steps to reproduce:**
Follow the steps as described above or in the udemy course, on system similar to mine (versions are listed below)

```
[err.txt](https://github.com/Postavshik/ngx-cypress-test/files/9497769/err.txt)
```

### Other information:

**npm, node, OS, IDE**
```
node version: v16.17.0
npm version: 8.15.0
Windows 10
Webstorm 2022.2.1
```

**Comment by carlszen** [comment]
In support of ghost's observation, I attempted to install this project to do some training.  There are >60 vulnerabilities with packages.  I had resolved down to six and blocked as to I do not know the importance of these packages.  I consider this project unsafe to train new developers.

**Comment by Patrick-Leeroy** [comment]
Had the same issue on my end

### Other information:
**npm, node, OS, IDE**

```
node version: v16.18.0
npm version: 8.19.2
MacOS 12.6
Visual Studio Code 1.72.2
```

**Comment by Postavshik** [comment]
@Patrick-Leeroy 
you probably have a dependencies conflict.
There are two ways to overcome this:
1. Delete the global node_modules folder from your computer, so it will not create a dependencies conflict. Also clean node cache with "npm cache clean --force"
2. You can use --force flag when doing the installation. This flag will just ignore the dependencies conflicts and everything will work just fine.

@carlszen this project is completely running on the localhost and does not do any interactions over APIs or something. It's just a dummy UI. You see those npm warnings, just because this project originally created in 2019 and npm thinks that because of some packages not updated - it creates vulnerability. But as I said - it's a dummy project. Just a UI running in your browser.
